package hudson.plugins.gradle.injection;

public final class GlobalEnvironmentVariables {

    // Common environment variables
    public static final String GRADLE_ENTERPRISE_INJECTION = "JENKINSGRADLEPLUGIN_GRADLE_ENTERPRISE_INJECTION";
    public static final String GRADLE_ENTERPRISE_ALLOW_UNTRUSTED_SERVER = "JENKINSGRADLEPLUGIN_GRADLE_ENTERPRISE_ALLOW_UNTRUSTED_SERVER";
    public static final String GRADLE_ENTERPRISE_URL = "JENKINSGRADLEPLUGIN_GRADLE_ENTERPRISE_URL";

    // Maven extension specific variables
    public static final String GRADLE_ENTERPRISE_EXTENSION_VERSION = "JENKINSGRADLEPLUGIN_GRADLE_ENTERPRISE_EXTENSION_VERSION";
    public static final String GRADLE_ENTERPRISE_CCUD_EXTENSION_VERSION = "JENKINSGRADLEPLUGIN_CCUD_EXTENSION_VERSION";
    public static final String MAVEN_INJECTION_DISABLED_NODES = "JENKINSGRADLEPLUGIN_MAVEN_INJECTION_DISABLED_NODES";
    public static final String MAVEN_INJECTION_ENABLED_NODES = "JENKINSGRADLEPLUGIN_MAVEN_INJECTION_ENABLED_NODES";

    // Gradle plugin specific variables
    public static final String BUILD_SCAN_OVERRIDE_GRADLE_HOME = "JENKINSGRADLEPLUGIN_BUILD_SCAN_OVERRIDE_GRADLE_HOME";
    public static final String BUILD_SCAN_OVERRIDE_HOME = "JENKINSGRADLEPLUGIN_BUILD_SCAN_OVERRIDE_HOME";
    public static final String GRADLE_ENTERPRISE_PLUGIN_VERSION = "JENKINSGRADLEPLUGIN_GRADLE_ENTERPRISE_PLUGIN_VERSION";
    public static final String GRADLE_INJECTION_DISABLED_NODES = "JENKINSGRADLEPLUGIN_GRADLE_INJECTION_DISABLED_NODES";
    public static final String GRADLE_INJECTION_ENABLED_NODES = "JENKINSGRADLEPLUGIN_GRADLE_INJECTION_ENABLED_NODES";

    private GlobalEnvironmentVariables() {
    }
}
